### ISSUE TITLE
Trouble with pyelmer.gmsh

### ISSUE THREAD

**Issue by Blue-Spartan** [nemocrys/pyelmer#10]
Hello,
This issue seems basic, but I am having trouble finding the pyelmer.gmsh module- I followed all the steps to download/install pyelmer to my IDE, but I cannot fix this issue. I searched inside the internal function but could not locate the module as stated.
- I ran the example code of a simple heat transfer simulation

Thanks,
Jaden C.

**Comment by mjfwest** [comment]
I've the same problem, so how was this closed? What was the solution?

**Comment by Blue-Spartan** [comment]
> I've the same problem, so how was this closed? What was the solution?

Switch to the module from pyelmer.gmsh to objectgmsh

**Comment by Blue-Spartan** [comment]
> I've the same problem, so how was this closed? What was the solution?

Switch the module from pyelmer.gmsh to objectgmsh

**Comment by arvedes** [comment]
Hi, sorry for the late reply. I recently did some refactoring and moved this code to a new project, as it is not related to Elmer but a convenience wrapper for Gmsh. I'll adjust the examples, thanks for letting me know!
