### ISSUE TITLE
Missing support for several solvers

### ISSUE THREAD

**Issue by kdadzis** [nemocrys/pyelmer#5]
I would like to set up a multi-physics simulation in pyelmer. This involves HeatSolve, FlowSolve, StressSolve, MagnetoDynamics, MagnetoDynamics2D, MeshSolve, SaveData and probably a few more post-processing solvers. Boundary conditions, body forces, etc., are currently not specified, i.e., need to be flexible in my case. Which solvers currently are supported by pyelmer and what are plans for the near future? I would like to install pyelmer in a package folder shared between several users and set-up/run my simulations without changing pyelmer itself.

**Comment by arvedes** [comment]
Multiple solvers are supported, as you can see in [this example](https://github.com/nemocrys/pyelmer/blob/master/examples/crystal_growth_2d.py#L109). If the solver you need is not available to be loaded you can [specify the settings on your own](https://github.com/nemocrys/pyelmer/blob/master/examples/heat_transfer_2d_manual.py#L66) or load it from a local yaml-file. You're welcome to add new solver specifications to [data/solvers.yml](https://github.com/nemocrys/pyelmer/blob/master/pyelmer/data/solvers.yml). Just open a pull request.

Installation is managed by [pip](https://pip.pypa.io/en/stable/cli/).
