### ISSUE TITLE
Basic problem getting pyelmer running

### ISSUE THREAD

**Issue by kottonau** [nemocrys/pyelmer#9]
On windows 10, python 3.10, installed pyelmer with pip command, we are getting the following error after trying to run one of the example scripts:

```
Traceback (most recent call last):
  File "path to\crystal_growth_2d.py", line 14, in <module>
    from pyelmer import elmer
  File "path to\Python310\site-packages\pyelmer\__init__.py", line 2, in <module>
    from . import elmer, execute, gmsh, post
  File "path to\Python310\site-packages\pyelmer\gmsh.py", line 4, in <module>    
    import gmsh
  File "path to\Python310\site-packages\gmsh.py", line 53, in <module>
    lib = CDLL(libpath)
  File "path to\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
```
Any hints?

**Comment by arvedes** [comment]
This seems to me like an issue with gmsh, which is used in the simulation setup.

Does `import gmsh` lead to the same issue?

**Comment by kottonau** [comment]
Yes indeed, same error. Do we need to use a specific version?

```
Name: gmsh
Version: 4.10.3
```

**Comment by arvedes** [comment]
I've been mostly working with version 4.8.4 (I used it when I set up the tutorial case), recently I updated to 4.10.1, both worked well. I'd recommend to first try 4.10.4 (it was released yesterday), if that doesn't help I'd go for the older versions.

Maybe there is already a corresponding [gmsh issue](https://gitlab.onelab.info/groups/gmsh/-/issues)?

**Comment by kottonau** [comment]
Reinstalled python, all seems to work now

```
python: 3.10.5
gmsh: 4.10.4
```

Looking forward to working with `pyelmer`!

**Comment by kottonau** [comment]
closing issue.
